routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function(){
	return redirect()->route('home');
});
Route::get('/home', function(){
	return redirect()->route('home');
});
Route::get('/dashboard', 'HomeController@index')->name('home');
Route::get('/produtos', 'ProdutoController@produtos')->name('produtos');
Route::get('/produtos/{produto}/detalhes', 'ProdutoController@detalhes')->name('produtos.detalhes');
Route::get('/estatisticas', 'ProdutoController@estatisticas')->name('estatisticas');

Route::post('/produtos/getData', 'ProdutoController@dataProduto')->name('produtos.data');
Route::post('/produtos/donutCategorias', 'ProdutoController@donutCategorias');
Route::post('/produtos/lineVarCategorias', 'ProdutoController@lineVarCategorias');

Route::get('/sobre', 'TextoController@index')->name('sobre');



Route::group(['middleware'=>'auth'], function(){
	Route::get('/produtos/{produto}/edit', 'ProdutoController@edit')->name('produtos.edit');
	Route::post('/produtos/{produto}/update', 'ProdutoController@update')->name('produtos.update');

	Route::get('/sobre/{texto}/edit', 'TextoController@edit')->name('sobre.edit');
	Route::post('/sobre/{texto}/update', 'TextoController@update')->name('sobre.update');
});

Auth::routes();

app/Produto.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;

class Produto extends Model
{
    protected $table = 'produtos';
    protected $dates = ['criado_em'];

    public function getFullUrlFotoAttribute($value)
    {
    	return $this->url_foto ? Storage::disk('public')->url($this->url_foto) : null;
    }
}

app/Http/Controllers/ProdutoController.php
<?php

namespace App\Http\Controllers;

use App\Produto;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class ProdutoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function produtos()
    {
        $produtos = Produto::all();
        return view('produtos.index', compact('produtos'));
    }

    public function detalhes($produtoId)
    {
    	$produtoBase = Produto::find($produtoId);
    	$produtos = Produto::where('url',$produtoBase->url)->orderBy("criado_em")->get();
    	
        return view('produtos.observacoes', compact('produtos', 'produtoBase'));	
    }

    public function edit($id){
    	$produto = Produto::find($id);
		return view('produtos.edit', compact('produto')); 
    }

    public function update(Request $request){

    	$produtos = Produto::where('url', $request->url)->get();
 
    	if ($request->has('url_foto')) {
    		if ($produtos->first()->url_foto && Storage::disk('public')->exists($produtos->first()->url_foto)) {
				Storage::disk('public')->delete($produtos->first()->url_foto);
			}
			$url_foto = Storage::disk('public')->putFile('produtos/', $request->file('url_foto'));
			Produto::where('url', $request->url)->update([
	    		'categoria'=>$request->categoria,
	    		'url_foto'=> $url_foto,
	    	]);
    	}else{
    		if($request->has('categoria')){
				Produto::where('url', $request->url)->update([
		    		'categoria'=>$request->categoria
		    	]);
    		}else{
    			$url_foto = Storage::disk('public')->putFile('produtos/', $request->file('url_foto'));
				Produto::where('url', $request->url)->update([
		    		'url_foto'=> $url_foto,
		    	]);
    		}
    	}

    	return redirect()->route('produtos')->with([
        	'status' => 'success',
        	'message' => 'Produtos editados!'
        ]);
    }

    public function estatisticas()
    {
    	$produtos = Produto::all()->groupBy(function($date) {
	        return Carbon::parse($date->criado_em)->format('d');
	    });

		return view('estatisticas', compact('produtos'));	
    }

    public function dataProduto(Request $request)
    {
    	$produtos = Produto::where('url',$request->url)->get()->sortBy('criado_em');
    	$labels = [];
    	$precos = [];
    	foreach ($produtos as $produto) {
    		array_push($labels, $produto->criado_em->format('d-M'));
    		array_push($precos, $produto->preco);
    	}
    	$bgs =[
    		'#FF6633', '#FFB399', '#FF33FF', '#FFFF99', '#00B3E6', 
			'#E6B333', '#3366E6', '#999966', '#99FF99', '#B34D4D',
			'#80B300', '#809900', '#E6B3B3', '#6680B3', '#66991A', 
			'#FF99E6', '#CCFF1A', '#FF1A66', '#E6331A', '#33FFCC',
			'#66994D', '#B366CC', '#4D8000', '#B33300', '#CC80CC', 
			'#66664D', '#991AFF', '#E666FF', '#4DB3FF', '#1AB399',
			'#E666B3', '#33991A', '#CC9999', '#B3B31A', '#00E680', 
			'#4D8066', '#809980', '#E6FF80', '#1AFF33', '#999933',
			'#FF3380', '#CCCC00', '#66E64D', '#4D80CC', '#9900B3', 
			'#E64D66', '#4DB380', '#FF4D4D', '#99E6E6', '#6666FF'
		];
    	$bg = array_rand($bgs);
    	$data = [
    		'background' => $bgs[$bg],
    		'produto' => $produtos->first(),
    		'labels' => $labels,
    		'precos' => $precos
    	];
    	return response()->json($data, 200, [], JSON_PRETTY_PRINT);
    }

    public function donutCategorias()
    {
      	$produtos = Produto::all()->groupBy('categoria');
      	
    	$labels = [];
    	$categorias = [];
    	
    	foreach ($produtos as $key => $produtosCat) {
    		array_push($labels, str_replace('_', ' ', ucfirst($key)));
    		array_push($categorias, $produtosCat->count());
    	}
    	$data = [
    		'labels' => $labels,
    		'categorias' => $categorias
    	];
    	return response()->json($data, 200, [], JSON_PRETTY_PRINT);
    }

    public function lineVarCategorias()
    {
    	$produtos = Produto::all();

    	$labels = [];

    	$teste = $produtos->sortBy('criado_em')->groupBy(function($date) {
	        return Carbon::parse($date->criado_em)->format('d-M');
	    });
    	foreach ($teste as $data => $produtos) {
    		array_push($labels, $data);
    	}

		$datasets = [];
		$colors = ["#3e95cd", "#8e5ea2","#3cba9f","#e8c3b9","#c45850","##a83232","#a0a832"];
		$colorId = 0;
    	foreach (Produto::all()->sortBy('created_at')->groupBy('categoria') as $categoria => $produtosPorCat) {

    		$produtosNovo = $produtosPorCat->sortBy('criado_em')->groupBy(function($date) {
		        return Carbon::parse($date->criado_em)->format('d-M');
		    });

    		$valores = [];
		    foreach ($produtosNovo as $data => $produtosDaData) {
		    	array_push($valores, $produtosDaData->pluck('preco')->sum());
		    }

		    $dataset['data'] = $valores;
			$dataset['label'] = str_replace('_', ' ', ucfirst($categoria));
			$dataset['borderColor'] = $colors[$colorId];
			$dataset['fill'] = false;
			array_push($datasets, $dataset);
    		$colorId++;
    	}

    	$data = [
    		'labels' => $labels,
    		'datasets' => $datasets
    	];
    	return response()->json($data, 200, [], JSON_PRETTY_PRINT);
    }
}

resources/views/produtos/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container-fluid">
    <div class="row justify-content-center">
    	@include('partials.sidebar')
        <div class="col-md-9">
            <div class="card">
                <div class="card-header d-flex">
                	<span class="align-self-center">Editar <strong>{{ $produto->nome }}</strong></span>
                </div>
				
                <div class="card-body">
                	<div class="form-group">
	                	<form action="{{ route('produtos.update', ['produto'=>$produto->id]) }}" method="POST" enctype="multipart/form-data">
	                		@csrf
	                		<input type="hidden" name="url" value="{{ $produto->url }}">
	                		<div class="row">
	                			<div class="col-md-4">
	                				<div class="form-group col-12">
				                        <label for="categoria">Categoria</label>
				                       	<select class="form-control" name="categoria" id="">
				                       		<option disabled>Selecione...</option>
				                       		<option value="flores">Flores</option>
				                       		<option value="calcados">Calçados</option>
				                       		<option value="perfumes">Perfumes</option>
				                       		<option value="aparelhos_celulares">Aparelhos Celulares</option>
				                       		<option value="moda">Moda</option>
				                       		<option value="eletroportateis">Eletroportáteis</option>
				                       		<option value="alimento">Alimento</option>
				                       	</select>
				                    </div>
	                			</div>
	                			<div class="col-md-2 align-content-center justify-content-center">
	                				<div class="col-md-12 justify-content-center align-content-center">
								    	<img src="{{ (isset($produto) && $produto->full_url_foto) ? $produto->full_url_foto : 'https://fakeimg.pl/300/?text==)' }}" alt="" class="img-thumbnail">
								    </div>
								    <div class="col-md-12 pt-3">
								    	<input type="file" name="url_foto" class="custom-file-input upload-input" id="url_foto" style="display: none;">
								    	<label for="url_foto" class="btn btn-outline-secondary col-12 upload-button form-control {{ $errors->has('url_foto') ? 'is-invalid' : '' }}">{{ (isset($produto) && $produto->full_url_foto) ? 'Trocar foto' : 'Selecionar foto' }}</label>
								    	@if ($errors->has('url_foto'))
								            <span class="invalid-feedback" role="alert">
								                <strong>{{ $errors->first('url_foto') }}</strong>
								            </span>
								        @endif
								    </div>
							    </div>
	                		</div>
                			<button type="submit" class="btn btn-primary preloader">Atualizar</button>	
	                	</form>
	                </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/produtos/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container-fluid">
    <div class="row justify-content-center">
    	@include('partials.sidebar')
        <div class="col-md-9">
            <div class="card">
                <div class="card-header d-flex">
                	<span class="align-self-center">Produtos</span>
                </div>

                <div class="card-body p-0">
					<table class="table">
						<thead>
							<tr>
								<th colspan="2">No.</th>
								<th>Nome</th>
								<th>Categoria</th>
								<th>Ultima coleta</th>
								<th>Variação acumulada</th>
							</tr>
						</thead>
						<tbody>
							@forelse ($produtos->groupBy('url') as $produto)
								<tr>
									<td class="pr-0">{{ $loop->iteration }}</td>
									<td class="px-0" style="width: 80px">
										<div class="col-md-12 p-0 text-center">
											<img src="{{ $produto->first()->full_url_foto ? $produto->first()->full_url_foto : 'https://fakeimg.pl/300/?txt==)' }}" alt="" class="img-fluid" style="width: 50px">
										</div>
									</td>
									<td>
										{{ $produto->first()->nome }}
										<div class="row">
											<div class="col-12">
												<ul class="table-actions px-0">
													<li>
														<a href="{{ $produto->first()->url }}" target="_blank">Visitar site</a>
													</li>
													<li>
														<a href="{{ route('produtos.detalhes', ['produto'=>$produto->first()->id]) }}">Observações</a>
													</li>
													@auth
														<li>
															<a href="{{ route('produtos.edit', ['produto'=>$produto->first()->id]) }}">Editar</a>
														</li>
													@endauth
												</ul>
											</div>
										</div>
									</td>
									<td>{{ ucfirst($produto->first()->categoria) }}</td>
									<td class="text-center">
										@php
											if($produto->first()->preco != 0){
												$variacaoDia1 = round((($produto->last()->preco - $produto->first()->preco)/$produto->first()->preco)*100, 2);
												if ($variacaoDia1 < 0) {
													$classVariacao = 'text-danger';
												}elseif($variacaoDia1 > 0){
													$classVariacao = 'text-success';
												}else{
													$classVariacao = '';
												}
											}else{
												$classVariacao = '';
												$variacaoDia1 = '-';
											}
										
										@endphp
										<strong class="{{ $classVariacao }}">{{ $variacaoDia1 }}%</strong>
										
									</td>
									<td class="text-center">
										@php
																		
											if($produto->get($produto->count() - 2) && $produto->get($produto->count() - 2)->preco != 0){
												$variacaoDiaria = round((($produto->last()->preco - $produto->get($produto->count() - 2)->preco)/$produto->get($produto->count() - 2)->preco)*100, 2);
												if ($variacaoDiaria < 0) {
													$classVariacaoDia = 'text-danger';
												}elseif($variacaoDiaria > 0){
													$classVariacaoDia = 'text-success';
												}else{
													$classVariacaoDia = '';
												}
											}else{
												$classVariacaoDia = '';
												$variacaoDiaria = '-';
											}
										@endphp
										<strong class="{{ $classVariacaoDia }}">{{ $variacaoDiaria }}%</strong>
									</td>
								</tr>
							@empty
								<tr class="odd"><td valign="top" colspan="3" class="dataTables_empty">Nenhum registro encontrado</td></tr>	
							@endforelse
						</tbody>
					</table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/produtos/observacoes.blade.php
@extends('layouts.app')

@section('content')
<div class="container-fluid">
    <div class="row justify-content-center">
    	@include('partials.sidebar')
        <div class="col-md-9">
        	<input type="hidden" id="urlProduto" value="{{ $produtoBase->url }}">
        	<div class="card">
        		<div class="card-header">
        			<canvas id="singleProduct" class="d-block w-100" height="250"></canvas>
        		</div>
        	</div>
            <div class="card">
                <div class="card-header d-flex">
                	<span class="align-self-center">Observações para <strong>{{ $produtoBase->nome }}</strong></span>
                </div>

                <div class="card-body p-0">
					<table class="table">
						<thead>
							<tr>
								<th>Coleta</th>
								<th>Preço</th>
								<th>Variacao diaria</th>
								<th>Data da coleta</th>
							</tr>
						</thead>
						<tbody>
							@forelse ($produtos as $produto)
								@php
								if($loop->iteration != 1 && $produtos->get($loop->iteration - 2)->preco != 0 && $produto->preco != 0){
									$variacaoDiaria = $loop->iteration != 1 ? round((($produto->preco / $produtos->get($loop->iteration - 2)->preco)-1)*100, 2)."%" : "-";
									if($variacaoDiaria > 0){
										$classVariacao = 'text-success';
									}elseif($variacaoDiaria < 0){
										$classVariacao = 'text-danger';
									}else{
										$classVariacao = '';
									}
								}else{
									if ($produto->preco == 0) {
										$variacaoDiaria = 'Produto indisponível';
									
										$classVariacao = '';
									}else{
										$variacaoDiaria = 'N/A';
										$classVariacao = '';
									}
									
								}
								@endphp
								<tr>
									<td>{{ $loop->iteration }}</td>
									<td>R$ {{ $produto->preco }}</td>
									<td><strong class="{{ $classVariacao }}">{{ $variacaoDiaria }}</strong></td>
									<td>{{ $produto->criado_em->format('d-M') }}</td>
								</tr>
							@empty
								<tr class="odd"><td valign="top" colspan="3" class="dataTables_empty">Nenhum registro encontrado</td></tr>	
							@endforelse
						</tbody>
					</table>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection